version: '3'

volumes:
  wordpress_storage:
    external: false
  mariadb_storage:
    external: false
  redis_storage:
    external: false
  image_storage:
    external: false

services:

  web:
    image: mitt-distrikt/web:latest
    volumes:
      - ../app:/entrypoint
      - ../config/app-config.js:/entrypoint/app-config.js:ro
      - image_storage:/uploads
    links: 
      - redis
    command: sh start-server.sh
      
  wordpress:
    image: mitt-distrikt/wordpress:latest
    environment:
      WORDPRESS_DB_PASSWORD: mmdNargzcoXMctLwdzdL
    volumes:
      - wordpress_storage:/var/www/html/wp-content/uploads
  
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mmdNargzcoXMctLwdzdL
    volumes:
      - mariadb_storage:/var/lib/mysql

  redis:
    image: mitt-distrikt/redis:latest
    volumes:
      - ../config/redis.conf:/tmp/redis.conf:ro
      - redis_storage:/redis_storage
    command: redis-server /tmp/redis.conf
  
  nginx:
    image: mitt-distrikt/nginx:latest
    links:
      - web
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../config/ssl_certificate.pem:/etc/nginx/ssl_certificate.pem
      - ../config/ssl_certificate.key:/etc/nginx/ssl_certificate.key
      - ../config/dhparams.pem:/etc/nginx/dhparams.pem
    command: nginx

